const C = {
	ADD_MARKER_CLICK_LISTENER: 'ADD_MARKER_CLICK_LISTENER',
	ADD_LABEL_CLICK_LISTENER: 'ADD_LABEL_CLICK_LISTENER',
	REPOSITION_MARKER_CLICK_LISTENER: 'REPOSITION_MARKER_CLICK_LISTENER',
}

export default C;